name: Node.js CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Set up pnpm in PATH
        run: echo "$HOME/.npm-global/bin" >> $GITHUB_ENV
      - name: Check pnpm version
        run: pnpm --version
      - run: pnpm install
      - run: pnpm run build
      - run: pm2 restart react-web3-nft